version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-rs0
    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongoContainerVPS

    command: >
      mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile

    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo-keyfile:/etc/mongo-keyfile:ro

volumes:
  mongo_data:
