version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    command:
      - "--replSet=rs0"
      - "--bind_ip_all"
      - "--keyFile=/etc/mongo-keyfile"
      - "--port=27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongoContainerVPS
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'rs.status().ok' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mongodb_data:
  mongodb_config:


networks:
  default:
    name: microserviceNetwork
