version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-rs0
    restart: always

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongoContainerVPS

    command: >
      bash -c " if [ ! -f /data/configdb/keyfile ]; then
        openssl rand -base64 756 > /data/configdb/keyfile;
        chmod 400 /data/configdb/keyfile;
      fi && mongod --replSet rs0 --bind_ip_all --keyFile /data/configdb/keyfile "

    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

volumes:
  mongo_data:
  mongo_config:
